# Generated by Django 2.0.1 on 2018-02-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alnindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('compfile', models.FileField(upload_to='')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
