# Generated by Django 2.0.1 on 2018-02-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0003_auto_20180207_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alnindex',
        ),
    ]
