# Generated by Django 2.0.1 on 2018-02-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0004_delete_alnindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paired_outputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_path', models.TextField()),
                ('SAM_path', models.TextField()),
                ('post_path', models.TextField()),
                ('VCF_path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Single_outputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_path', models.TextField()),
                ('SAM_path', models.TextField()),
                ('post_path', models.TextField()),
                ('VCF_path', models.TextField()),
            ],
        ),
    ]
