# Generated by Django 2.0.1 on 2018-02-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0005_paired_outputs_single_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_job',
            name='sreads_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
