# Generated by Django 2.0.1 on 2018-02-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0009_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singlejob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.TextField()),
                ('date', models.DateTimeField()),
                ('sreads_file', models.FileField(null=True, upload_to='align/read_uploads')),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('pre_path', models.TextField(null=True)),
                ('SAM_path', models.TextField(null=True)),
                ('post_path', models.TextField(null=True)),
                ('VCF_path', models.TextField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Paired_job',
            new_name='Pairedjob',
        ),
        migrations.DeleteModel(
            name='Single_job',
        ),
    ]
