# Generated by Django 2.0.1 on 2018-02-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0010_auto_20180212_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Single_outputs',
        ),
        migrations.AlterField(
            model_name='singlejob',
            name='sreads_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
