# Generated by Django 2.0.2 on 2018-02-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0011_auto_20180212_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlejob',
            name='userkey',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='singlejob',
            name='original_filename',
            field=models.TextField(null=True),
        ),
    ]
