# Generated by Django 2.0.2 on 2018-02-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0013_auto_20180216_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairedjob',
            name='adapters',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pairedjob',
            name='key',
            field=models.TextField(null=True),
        ),
    ]
