# Generated by Django 2.0.2 on 2018-02-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0015_auto_20180216_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paired_outputs',
        ),
        migrations.RenameField(
            model_name='singlejob',
            old_name='sreads_file',
            new_name='readsfile',
        ),
        migrations.RemoveField(
            model_name='singlejob',
            name='SAM_path',
        ),
        migrations.RemoveField(
            model_name='singlejob',
            name='VCF_path',
        ),
        migrations.RemoveField(
            model_name='singlejob',
            name='date',
        ),
        migrations.RemoveField(
            model_name='singlejob',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='singlejob',
            name='post_path',
        ),
        migrations.RemoveField(
            model_name='singlejob',
            name='pre_path',
        ),
        migrations.RemoveField(
            model_name='singlejob',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='singlejob',
            name='userkey',
        ),
        migrations.AddField(
            model_name='singlejob',
            name='adapters',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='singlejob',
            name='key',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
