# Generated by Django 2.0.2 on 2018-02-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0016_auto_20180216_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlejob',
            name='adapters',
        ),
        migrations.RemoveField(
            model_name='singlejob',
            name='readsfile',
        ),
        migrations.AlterField(
            model_name='singlejob',
            name='key',
            field=models.CharField(max_length=50),
        ),
    ]
