# Generated by Django 2.0.2 on 2018-02-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0017_auto_20180216_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlejob',
            name='key',
        ),
        migrations.AddField(
            model_name='singlejob',
            name='readsfile',
            field=models.FileField(default='/project/home17/whb17/public_html/randtestreads.fasta', upload_to=''),
        ),
    ]
