# Generated by Django 2.0.2 on 2018-02-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0018_auto_20180216_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlejob',
            name='user_email',
            field=models.EmailField(default='whb17@ic.ac.uk', max_length=254),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='user_email',
            field=models.EmailField(default='whb17@ic.ac.uk', max_length=254),
        ),
    ]
