# Generated by Django 2.0.2 on 2018-02-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0020_auto_20180219_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='title',
        ),
    ]
